"""Initial audited scanner schema"""

import sqlalchemy as sa

from alembic import op

revision = "efb2041d5699"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_sessions",
        sa.Column("expires_epoch", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_admin_sessions_created_at"), "admin_sessions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_admin_sessions_expires_epoch"), "admin_sessions", ["expires_epoch"], unique=False
    )
    op.create_index(op.f("ix_admin_sessions_source"), "admin_sessions", ["source"], unique=False)
    op.create_table(
        "alerts",
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_created_at"), "alerts", ["created_at"], unique=False)
    op.create_index(op.f("ix_alerts_source"), "alerts", ["source"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_created_at"), "audit_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_events_source"), "audit_events", ["source"], unique=False)
    op.create_table(
        "auth_rate_limits",
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("expires_epoch", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "canonical_sports_events",
        sa.Column("league", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_canonical_sports_events_created_at"),
        "canonical_sports_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_sports_events_league"),
        "canonical_sports_events",
        ["league"],
        unique=False,
    )
    op.create_index(
        op.f("ix_canonical_sports_events_source"),
        "canonical_sports_events",
        ["source"],
        unique=False,
    )
    op.create_table(
        "daily_statistics",
        sa.Column("day", sa.String(length=10), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_daily_statistics_created_at"), "daily_statistics", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_daily_statistics_day"), "daily_statistics", ["day"], unique=False)
    op.create_index(
        op.f("ix_daily_statistics_source"), "daily_statistics", ["source"], unique=False
    )
    op.create_table(
        "opportunity_observations",
        sa.Column("opportunity_id", sa.String(length=160), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_opportunity_observations_created_at"),
        "opportunity_observations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_observations_opportunity_id"),
        "opportunity_observations",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_observations_source"),
        "opportunity_observations",
        ["source"],
        unique=False,
    )
    op.create_table(
        "opportunity_rejections",
        sa.Column("match_id", sa.String(length=160), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_opportunity_rejections_created_at"),
        "opportunity_rejections",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_rejections_match_id"),
        "opportunity_rejections",
        ["match_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_rejections_reason"), "opportunity_rejections", ["reason"], unique=False
    )
    op.create_index(
        op.f("ix_opportunity_rejections_source"), "opportunity_rejections", ["source"], unique=False
    )
    op.create_table(
        "risk_settings",
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_risk_settings_created_at"), "risk_settings", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_risk_settings_source"), "risk_settings", ["source"], unique=False)
    op.create_table(
        "system_events",
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_events_created_at"), "system_events", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_system_events_role"), "system_events", ["role"], unique=False)
    op.create_index(op.f("ix_system_events_source"), "system_events", ["source"], unique=False)
    op.create_table(
        "team_aliases",
        sa.Column("league", sa.String(length=32), nullable=False),
        sa.Column("original", sa.String(length=256), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("league", "original", "source"),
    )
    op.create_index(
        op.f("ix_team_aliases_created_at"), "team_aliases", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_team_aliases_source"), "team_aliases", ["source"], unique=False)
    op.create_table(
        "venue_health",
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue"),
    )
    op.create_index(
        op.f("ix_venue_health_created_at"), "venue_health", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_venue_health_source"), "venue_health", ["source"], unique=False)
    op.create_table(
        "venue_markets",
        sa.Column("venue", sa.String(length=32), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=False),
        sa.Column("league", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("rules_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("venue", "external_id", "source"),
    )
    op.create_index(
        op.f("ix_venue_markets_created_at"), "venue_markets", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_venue_markets_league"), "venue_markets", ["league"], unique=False)
    op.create_index(op.f("ix_venue_markets_source"), "venue_markets", ["source"], unique=False)
    op.create_index(op.f("ix_venue_markets_status"), "venue_markets", ["status"], unique=False)
    op.create_index(op.f("ix_venue_markets_venue"), "venue_markets", ["venue"], unique=False)
    op.create_table(
        "worker_heartbeats",
        sa.Column("role", sa.String(length=64), nullable=False),
        sa.Column("owner", sa.String(length=64), nullable=False),
        sa.Column("expires_epoch", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("role"),
    )
    op.create_index(
        op.f("ix_worker_heartbeats_created_at"), "worker_heartbeats", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_worker_heartbeats_source"), "worker_heartbeats", ["source"], unique=False
    )
    op.create_table(
        "contract_specification_versions",
        sa.Column("market_id", sa.String(length=160), nullable=False),
        sa.Column("rules_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["venue_markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "rules_hash"),
    )
    op.create_index(
        op.f("ix_contract_specification_versions_created_at"),
        "contract_specification_versions",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_specification_versions_market_id"),
        "contract_specification_versions",
        ["market_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_contract_specification_versions_source"),
        "contract_specification_versions",
        ["source"],
        unique=False,
    )
    op.create_table(
        "current_orderbooks",
        sa.Column("market_id", sa.String(length=160), nullable=False),
        sa.Column("outcome", sa.String(length=8), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["venue_markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id", "outcome", "source"),
    )
    op.create_index(
        op.f("ix_current_orderbooks_created_at"), "current_orderbooks", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_current_orderbooks_market_id"), "current_orderbooks", ["market_id"], unique=False
    )
    op.create_index(
        op.f("ix_current_orderbooks_source"), "current_orderbooks", ["source"], unique=False
    )
    op.create_table(
        "market_annotations",
        sa.Column("market_id", sa.String(length=160), nullable=False),
        sa.Column("raw_rules_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["venue_markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("market_id"),
    )
    op.create_index(
        op.f("ix_market_annotations_created_at"), "market_annotations", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_market_annotations_source"), "market_annotations", ["source"], unique=False
    )
    op.create_table(
        "market_matches",
        sa.Column("event_id", sa.String(length=160), nullable=False),
        sa.Column("first_market_id", sa.String(length=160), nullable=False),
        sa.Column("second_market_id", sa.String(length=160), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("current", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["canonical_sports_events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["first_market_id"],
            ["venue_markets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["second_market_id"],
            ["venue_markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_matches_created_at"), "market_matches", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_market_matches_event_id"), "market_matches", ["event_id"], unique=False
    )
    op.create_index(
        op.f("ix_market_matches_first_market_id"),
        "market_matches",
        ["first_market_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_matches_second_market_id"),
        "market_matches",
        ["second_market_id"],
        unique=False,
    )
    op.create_index(op.f("ix_market_matches_source"), "market_matches", ["source"], unique=False)
    op.create_index(op.f("ix_market_matches_status"), "market_matches", ["status"], unique=False)
    op.create_index(
        "ix_match_pair_current",
        "market_matches",
        ["first_market_id", "second_market_id", "current"],
        unique=False,
    )
    op.create_table(
        "orderbook_snapshots",
        sa.Column("market_id", sa.String(length=160), nullable=False),
        sa.Column("outcome", sa.String(length=8), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_id"],
            ["venue_markets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orderbook_snapshots_created_at"),
        "orderbook_snapshots",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_orderbook_snapshots_market_id"), "orderbook_snapshots", ["market_id"], unique=False
    )
    op.create_index(
        op.f("ix_orderbook_snapshots_source"), "orderbook_snapshots", ["source"], unique=False
    )
    op.create_table(
        "arbitrage_opportunities",
        sa.Column("match_id", sa.String(length=160), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("league", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("net_profit", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("net_return", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("direction", sa.String(length=8), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["market_matches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_created_at"),
        "arbitrage_opportunities",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_direction"),
        "arbitrage_opportunities",
        ["direction"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_event_id"),
        "arbitrage_opportunities",
        ["event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_expires_at"),
        "arbitrage_opportunities",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_league"),
        "arbitrage_opportunities",
        ["league"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_match_id"),
        "arbitrage_opportunities",
        ["match_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_net_profit"),
        "arbitrage_opportunities",
        ["net_profit"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_net_return"),
        "arbitrage_opportunities",
        ["net_return"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_source"),
        "arbitrage_opportunities",
        ["source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_arbitrage_opportunities_status"),
        "arbitrage_opportunities",
        ["status"],
        unique=False,
    )
    op.create_table(
        "market_match_reviews",
        sa.Column("match_id", sa.String(length=160), nullable=False),
        sa.Column("actor", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["market_matches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_market_match_reviews_created_at"),
        "market_match_reviews",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_match_reviews_match_id"), "market_match_reviews", ["match_id"], unique=False
    )
    op.create_index(
        op.f("ix_market_match_reviews_source"), "market_match_reviews", ["source"], unique=False
    )
    op.create_table(
        "paper_trades",
        sa.Column("opportunity_id", sa.String(length=160), nullable=False),
        sa.Column("event_id", sa.String(length=64), nullable=False),
        sa.Column("league", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("reserved_capital", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["arbitrage_opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("opportunity_id"),
    )
    op.create_index(
        op.f("ix_paper_trades_created_at"), "paper_trades", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_paper_trades_event_id"), "paper_trades", ["event_id"], unique=False)
    op.create_index(op.f("ix_paper_trades_league"), "paper_trades", ["league"], unique=False)
    op.create_index(op.f("ix_paper_trades_source"), "paper_trades", ["source"], unique=False)
    op.create_index(op.f("ix_paper_trades_state"), "paper_trades", ["state"], unique=False)
    op.create_table(
        "paper_trade_legs",
        sa.Column("trade_id", sa.String(length=160), nullable=False),
        sa.Column("leg", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["paper_trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trade_id", "leg"),
    )
    op.create_index(
        op.f("ix_paper_trade_legs_created_at"), "paper_trade_legs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_paper_trade_legs_source"), "paper_trade_legs", ["source"], unique=False
    )
    op.create_index(
        op.f("ix_paper_trade_legs_trade_id"), "paper_trade_legs", ["trade_id"], unique=False
    )
    op.create_table(
        "replay_runs",
        sa.Column("trade_id", sa.String(length=160), nullable=True),
        sa.Column("id", sa.String(length=160), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["paper_trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_replay_runs_created_at"), "replay_runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_replay_runs_source"), "replay_runs", ["source"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_replay_runs_source"), table_name="replay_runs")
    op.drop_index(op.f("ix_replay_runs_created_at"), table_name="replay_runs")
    op.drop_table("replay_runs")
    op.drop_index(op.f("ix_paper_trade_legs_trade_id"), table_name="paper_trade_legs")
    op.drop_index(op.f("ix_paper_trade_legs_source"), table_name="paper_trade_legs")
    op.drop_index(op.f("ix_paper_trade_legs_created_at"), table_name="paper_trade_legs")
    op.drop_table("paper_trade_legs")
    op.drop_index(op.f("ix_paper_trades_state"), table_name="paper_trades")
    op.drop_index(op.f("ix_paper_trades_source"), table_name="paper_trades")
    op.drop_index(op.f("ix_paper_trades_league"), table_name="paper_trades")
    op.drop_index(op.f("ix_paper_trades_event_id"), table_name="paper_trades")
    op.drop_index(op.f("ix_paper_trades_created_at"), table_name="paper_trades")
    op.drop_table("paper_trades")
    op.drop_index(op.f("ix_market_match_reviews_source"), table_name="market_match_reviews")
    op.drop_index(op.f("ix_market_match_reviews_match_id"), table_name="market_match_reviews")
    op.drop_index(op.f("ix_market_match_reviews_created_at"), table_name="market_match_reviews")
    op.drop_table("market_match_reviews")
    op.drop_index(op.f("ix_arbitrage_opportunities_status"), table_name="arbitrage_opportunities")
    op.drop_index(op.f("ix_arbitrage_opportunities_source"), table_name="arbitrage_opportunities")
    op.drop_index(
        op.f("ix_arbitrage_opportunities_net_return"), table_name="arbitrage_opportunities"
    )
    op.drop_index(
        op.f("ix_arbitrage_opportunities_net_profit"), table_name="arbitrage_opportunities"
    )
    op.drop_index(op.f("ix_arbitrage_opportunities_match_id"), table_name="arbitrage_opportunities")
    op.drop_index(op.f("ix_arbitrage_opportunities_league"), table_name="arbitrage_opportunities")
    op.drop_index(
        op.f("ix_arbitrage_opportunities_expires_at"), table_name="arbitrage_opportunities"
    )
    op.drop_index(op.f("ix_arbitrage_opportunities_event_id"), table_name="arbitrage_opportunities")
    op.drop_index(
        op.f("ix_arbitrage_opportunities_direction"), table_name="arbitrage_opportunities"
    )
    op.drop_index(
        op.f("ix_arbitrage_opportunities_created_at"), table_name="arbitrage_opportunities"
    )
    op.drop_table("arbitrage_opportunities")
    op.drop_index(op.f("ix_orderbook_snapshots_source"), table_name="orderbook_snapshots")
    op.drop_index(op.f("ix_orderbook_snapshots_market_id"), table_name="orderbook_snapshots")
    op.drop_index(op.f("ix_orderbook_snapshots_created_at"), table_name="orderbook_snapshots")
    op.drop_table("orderbook_snapshots")
    op.drop_index("ix_match_pair_current", table_name="market_matches")
    op.drop_index(op.f("ix_market_matches_status"), table_name="market_matches")
    op.drop_index(op.f("ix_market_matches_source"), table_name="market_matches")
    op.drop_index(op.f("ix_market_matches_second_market_id"), table_name="market_matches")
    op.drop_index(op.f("ix_market_matches_first_market_id"), table_name="market_matches")
    op.drop_index(op.f("ix_market_matches_event_id"), table_name="market_matches")
    op.drop_index(op.f("ix_market_matches_created_at"), table_name="market_matches")
    op.drop_table("market_matches")
    op.drop_index(op.f("ix_market_annotations_source"), table_name="market_annotations")
    op.drop_index(op.f("ix_market_annotations_created_at"), table_name="market_annotations")
    op.drop_table("market_annotations")
    op.drop_index(op.f("ix_current_orderbooks_source"), table_name="current_orderbooks")
    op.drop_index(op.f("ix_current_orderbooks_market_id"), table_name="current_orderbooks")
    op.drop_index(op.f("ix_current_orderbooks_created_at"), table_name="current_orderbooks")
    op.drop_table("current_orderbooks")
    op.drop_index(
        op.f("ix_contract_specification_versions_source"),
        table_name="contract_specification_versions",
    )
    op.drop_index(
        op.f("ix_contract_specification_versions_market_id"),
        table_name="contract_specification_versions",
    )
    op.drop_index(
        op.f("ix_contract_specification_versions_created_at"),
        table_name="contract_specification_versions",
    )
    op.drop_table("contract_specification_versions")
    op.drop_index(op.f("ix_worker_heartbeats_source"), table_name="worker_heartbeats")
    op.drop_index(op.f("ix_worker_heartbeats_created_at"), table_name="worker_heartbeats")
    op.drop_table("worker_heartbeats")
    op.drop_index(op.f("ix_venue_markets_venue"), table_name="venue_markets")
    op.drop_index(op.f("ix_venue_markets_status"), table_name="venue_markets")
    op.drop_index(op.f("ix_venue_markets_source"), table_name="venue_markets")
    op.drop_index(op.f("ix_venue_markets_league"), table_name="venue_markets")
    op.drop_index(op.f("ix_venue_markets_created_at"), table_name="venue_markets")
    op.drop_table("venue_markets")
    op.drop_index(op.f("ix_venue_health_source"), table_name="venue_health")
    op.drop_index(op.f("ix_venue_health_created_at"), table_name="venue_health")
    op.drop_table("venue_health")
    op.drop_index(op.f("ix_team_aliases_source"), table_name="team_aliases")
    op.drop_index(op.f("ix_team_aliases_created_at"), table_name="team_aliases")
    op.drop_table("team_aliases")
    op.drop_index(op.f("ix_system_events_source"), table_name="system_events")
    op.drop_index(op.f("ix_system_events_role"), table_name="system_events")
    op.drop_index(op.f("ix_system_events_created_at"), table_name="system_events")
    op.drop_table("system_events")
    op.drop_index(op.f("ix_risk_settings_source"), table_name="risk_settings")
    op.drop_index(op.f("ix_risk_settings_created_at"), table_name="risk_settings")
    op.drop_table("risk_settings")
    op.drop_index(op.f("ix_opportunity_rejections_source"), table_name="opportunity_rejections")
    op.drop_index(op.f("ix_opportunity_rejections_reason"), table_name="opportunity_rejections")
    op.drop_index(op.f("ix_opportunity_rejections_match_id"), table_name="opportunity_rejections")
    op.drop_index(op.f("ix_opportunity_rejections_created_at"), table_name="opportunity_rejections")
    op.drop_table("opportunity_rejections")
    op.drop_index(op.f("ix_opportunity_observations_source"), table_name="opportunity_observations")
    op.drop_index(
        op.f("ix_opportunity_observations_opportunity_id"), table_name="opportunity_observations"
    )
    op.drop_index(
        op.f("ix_opportunity_observations_created_at"), table_name="opportunity_observations"
    )
    op.drop_table("opportunity_observations")
    op.drop_index(op.f("ix_daily_statistics_source"), table_name="daily_statistics")
    op.drop_index(op.f("ix_daily_statistics_day"), table_name="daily_statistics")
    op.drop_index(op.f("ix_daily_statistics_created_at"), table_name="daily_statistics")
    op.drop_table("daily_statistics")
    op.drop_index(op.f("ix_canonical_sports_events_source"), table_name="canonical_sports_events")
    op.drop_index(op.f("ix_canonical_sports_events_league"), table_name="canonical_sports_events")
    op.drop_index(
        op.f("ix_canonical_sports_events_created_at"), table_name="canonical_sports_events"
    )
    op.drop_table("canonical_sports_events")
    op.drop_table("auth_rate_limits")
    op.drop_index(op.f("ix_audit_events_source"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_created_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_alerts_source"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_created_at"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_admin_sessions_source"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_expires_epoch"), table_name="admin_sessions")
    op.drop_index(op.f("ix_admin_sessions_created_at"), table_name="admin_sessions")
    op.drop_table("admin_sessions")
    # ### end Alembic commands ###
